### Site metadata ###

title: Portfolio Website
description: Portfolio WEbsite

github_repo: renzgallarmen/rgallarmen.github.io

### Build settings ###

url: https://rgallarmen.github.io
baseurl: /portfolio-website

exclude:
  - vendor/
  - Gemfile
  - LICENSE
  - Makefile
  - README.md
  - sample*.png

liquid:
  error_mode: strict

strict_front_matter: true
